apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deploy
  labels:
    app: eureka-server
spec:
  selector:
    matchLabels:
      app: eureka-server
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server-container
        image: 9511/eureka-server-nishant-nagp:latest
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-server-nishant
  labels:
    app: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
