apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-supplier-service-deploy
  labels:
    app: flight-supplier-service
spec:
  selector:
    matchLabels:
      app: flight-supplier-service
  replicas: 1
  template:
    metadata:
      labels:
        app: flight-supplier-service
    spec:
      containers:
      - name: flight-supplier-service-container
        image: 9511/flight-supplier-service-nishant-nagp:latest
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: flight-supplier-service-nishant
  labels:
    app: flight-supplier-service
spec:
  selector:
    app: flight-supplier-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer
